// Code generated by "stringer -type=Programs"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[anki-0]
	_ = x[mpv-1]
	_ = x[ttsu-2]
	_ = x[asbplayer-3]
	_ = x[VLC-4]
}

const _Programs_name = "ankimpvttsuasbplayerVLC"

var _Programs_index = [...]uint8{0, 4, 7, 11, 20, 23}

func (i Programs) String() string {
	if i < 0 || i >= Programs(len(_Programs_index)-1) {
		return "Programs(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Programs_name[_Programs_index[i]:_Programs_index[i+1]]
}
